// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_E2ZITiKBEhMb32aCq1XjdL1wqzTfZpM',
    appId: '1:463337602635:android:2f697651b24707bab457ce',
    messagingSenderId: '463337602635',
    projectId: 'trafficstatus-app',
    storageBucket: 'trafficstatus-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeZwr5CKLG-1ownPXpiDcyhlYCSc5Zj4s',
    appId: '1:463337602635:ios:a81f490d29ee2f73b457ce',
    messagingSenderId: '463337602635',
    projectId: 'trafficstatus-app',
    storageBucket: 'trafficstatus-app.appspot.com',
    iosClientId: '463337602635-63h98h11lm6vqrlsptjuegf93779rskj.apps.googleusercontent.com',
    iosBundleId: 'com.trafficstatus.app',
  );
}
